### ISSUE TITLE
If a keyboard is open back_button_inceptor doesn't recognize the event

### ISSUE THREAD

**Issue by thorgexyz** [marcglasberg/back_button_interceptor#11]
First of all, thanks for this package.

Before I implemented the package, the back button closed the whole page when the keyboard was open.

Now I implemented the example code, now the keyboard gets closed when the back button is pressed. If it's pressed once more only then myInterceptor gets called (I am checking this with print statements)

Any idea why this might be the case or how I can change that? Thanks

**Comment by marcglasberg** [comment]
@ThorgeL When the keyboard is open, the back-button press should close it. That's expected behavior. I don't know how this is possible:

> Before I implemented the package, the back button closed the whole page when the keyboard was open.

Are you sure about it? Can you please provide me with some simple runnable code for me to test this behavior? Thanks!
