### ISSUE TITLE
Does this work with the material AppBar back button?

### ISSUE THREAD

**Issue by george-ayris** [marcglasberg/back_button_interceptor#2]
Hi there,

These library works wonderfully with the native Android back button, however, I'd also like the same behaviour when pressing the `AppBar` back button (from the `flutter/material.dart` package) and by default it doesn't appear to work. Is there a way to enable this behaviour?

Cheers,
George

**Comment by marcglasberg** [comment]
Hello George,

The AppBar is a regular widget which implements its own back function, probably by calling Navigator.pop(context);. I has nothing to do with the Android back-button, and as such is not the concern of the back_button_interceptor package.

So, I'm afraid I can't help you. I suggest you study this info: https://flutter.dev/docs/cookbook/navigation/navigation-basics

**Comment by george-ayris** [comment]
Thanks for your help.
