### ISSUE TITLE
Version 6.0.0 causes an error when the Dart SDK version is less than 1.17.0

### ISSUE THREAD

**Issue by yukisakai1225** [marcglasberg/back_button_interceptor#21]
WidgetsBinding.instance was changed to non-nullable in flutter3.0.
So, if the Dart SDK is less than 2.17.0, it will be treated as nullable.
Therefore Version 6.0.0  only supports Dart SDK 2.17.0 or higher.
I'm not good at English, so it may be hard to read, but thanks in advance.

**Comment by Lorenzohidalgo** [comment]
I can also confirm that the interceptor doesn't work correctly in my app after upgrading to flutter 3 and v6.0.0 in a non null-safe app.

**Comment by marcglasberg** [comment]
Yes, if you are using Flutter <3.0 or non nullsafe app, please fix it to version `5.1.0`.

I have upgraded the app to `6.0.1` and changed the environment to `sdk: '>=2.17.0 <3.0.0'`

**Comment by Lorenzohidalgo** [comment]
@marcglasberg, I'm currently running Flutter 3.0.3 but a null-safe app. Running it on 5.1.0 does return errors while building the app. Is there a version compatible with flutter 3 but non-nullsafe?

**Comment by marcglasberg** [comment]
@Lorenzohidalgo Sorry, it's not practical to keep supporting non-nullsafe apps. I suggest you upgrade your app to nullsafe, or that you keep using an older version of Flutter. Another alternative is for you to fork the repo, apply your changes, and then link your `pubspec.yaml` directly to your Git.
