### ISSUE TITLE
Suspected conflict with flow_builder

### ISSUE THREAD

**Issue by flodaniel** [marcglasberg/back_button_interceptor#23]
We are using the [flow_builder](https://pub.dev/packages/flow_builder) package which also uses the `SystemChannels.navigation.setMethodCallHandler();`. In addition we use the [loader_overlay](https://github.com/rodrigobastosv/loading_overlay) package, which uses this package.

 As soon as a BackButtonInterceptor is added, the flow_builder package stops to register android back button navigations. 

This is how flow_builder works with the SystemChannels.navigation: 

<img width="725" alt="image" src="https://user-images.githubusercontent.com/6661557/186466647-e0566213-7662-4dd6-8d5a-c7a3ce13c2ce.png">

The flow builder calls that class in initState
<img width="676" alt="image" src="https://user-images.githubusercontent.com/6661557/186466850-5117d058-98b1-4b80-a8d5-3953e3eff36f.png">

Based on documentation of `SystemChannels.navigation.setMethodCallHandler,` the one replaces the other: 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/6661557/186468178-c5441890-ad23-4c9b-beaa-6c0bb6fa650b.png">

**Comment by marcglasberg** [comment]
Yes, it seems it's using the same mechanism and conflicting. Sorry, but I don't intend on fixing this, as I don't use the flow_builder package. But feel free to PR a solution, if you know how to fix it. As long as it doesn't interfere with the way the interceptor works when the flow_builder is not being used.

**Comment by flodaniel** [comment]
@marcglasberg understandable. I hope that we can move flow_builder to your package, which should resolve the issue. 

https://github.com/felangel/flow_builder/issues/102
