### ISSUE TITLE
Not working with Android 13

### ISSUE THREAD

**Issue by fede1295** [marcglasberg/back_button_interceptor#26]
On android 13 the interceptor doesn't seem to work, backwards isn't really recognised.... this doesn't happen with android 12

**Comment by marcglasberg** [comment]
Ok, I'll test this as soon as I can. But that's a bit weird, as I'm only interacting with Dart code, not any native code.

**Comment by msxenon** [comment]
same issue

**Comment by msxenon** [comment]
found it, its working as expected but had to set this to false in android manifest `        android:enableOnBackInvokedCallback="false"
` 
you need to disable it so the back button callback will work as expected before

**Comment by marcglasberg** [comment]
@fede1295 Could you please try setting this to false in the Android manifest: `android:enableOnBackInvokedCallback="false"` ?

**Comment by marcglasberg** [comment]
I added this information to the documentation. Thanks @msxenon and @fede1295
