### ISSUE TITLE
Typo in the year of latest (7.0.2) version date

### ISSUE THREAD

**Issue by JesusHdez960717** [marcglasberg/back_button_interceptor#27]
Affect: **CHANGELOG.md**

Issue: Typo in the year of the date, is *2023* and should be *2024*.

Description: Latest available version at the moment is 7.0.2, and has date of `2023/02/07`, I assume its a typo and should be `2024/02/07`, specially since the former version has date `[7.0.1] - 2023/08/10`.

Note: Or it's a typo, or you guys discover time travel, so pls, share your knowledge with us :smile:

**Comment by marcglasberg** [comment]
Fixed. Thanks!
